const MOVIE_SHORT_FILM_DURATION = 40;
const TABLET_SCREEN_WIDTH = 1160;
const MOBILE_SCREEN_WIDTH = 720;
const LAPTOP_MOVIE_NUMBER = 12;
const TABLET_MOVIE_NUMBER = 8;
const MOBILE_MOVIE_NUMBER = 5;
const TABLET_MORE_MOVIES = 3;
const MOBILE_MORE_MOVIES = 2;



export {
    MOVIE_SHORT_FILM_DURATION,
    TABLET_SCREEN_WIDTH,
    MOBILE_SCREEN_WIDTH,
    LAPTOP_MOVIE_NUMBER,
    TABLET_MOVIE_NUMBER,
    MOBILE_MOVIE_NUMBER,
    TABLET_MORE_MOVIES,
    MOBILE_MORE_MOVIES,
}
